// <auto-generated />
namespace SwiftSkoolv1.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PrincipalComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrincipalComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201709251304392_PrincipalComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
