// <auto-generated />
namespace SwiftSkoolv1.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class examTYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(examTYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201802151509493_examTYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
